# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Patrick Skiba
email: pskiba@posteo.net
author: Patrick Skiba
social:
  name: Patrick Skiba
  links:
    - https://twitter.com/patrickskiba
    - https://github.com/Patrickskiba
    - https://www.instagram.com/skibap
    - https://www.linkedin.com/in/patrick-skiba-21a78410a/
    - https://news.ycombinator.com/user?id=pskiba
twitter:
  username: patrickskiba
  card: summary

logo: /assets/icons/favicon.ico

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patrickskiba.com" # the base hostname & protocol for your site, e.g. http://example.com
description: Patrick Skiba's personal website where he talks about topics he is interested in
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sitemap
